name: hexlet-ci-app
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

        # install poetry
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - run: poetry run pytest
      - run: poetry run flake8 gendiff
